name: untitled
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  super_cupertino_navigation_bar:
    path: ./..
  cupertino_icons: ^1.0.2
  modal_bottom_sheet: ^3.0.0-pre
  http: ^1.1.0
  flutter_rating_stars: ^1.0.3+4
  lottie: ^2.7.0
  marvelous_carousel: ^0.0.16

dependency_overrides:
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - "assets/"
